name: 'Deploy container environment stage'

on:
    workflow_dispatch:
    push:
        branches: [release]
        paths-ignore:
            - docs/**
            - README.md
            - .github/**
            - cloudformation/**
            - db_scripts/**
            - jenkins/**
            - search-proxy/**
            - postgresql/**
            - cloudformation/tests/**
            - concordia/tests/**
            - exporter/tests/**
            - importer/tests/**

env:
    AWS_REGION: us-east-1

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        name: Deploy Container Environment Update Stage
        runs-on: ubuntu-latest
        environment:
            name: stage

        steps:
            - name: Install system packages
              run: |
                  sudo apt-get update -qy && sudo apt-get dist-upgrade -qy && sudo apt-get install -qy \
                  libmemcached-dev libz-dev libfreetype6-dev libtiff-dev \
                  libjpeg-dev libopenjp2-7-dev libwebp-dev zlib1g-dev libpq-dev

            - name: Install node and npm
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: release
                  fetch-depth: 0
                  fetch-tags: 'true'

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  # Semantic version range syntax or exact version of a Python version
                  python-version: '3.12'
                  # Optional - x64 or x86 architecture, defaults to x64
                  architecture: 'x64'

            - name: Create image tags
              run: |
                  # Get latest version tag number (e.g. main was tagged in GitHub for this Release)
                  FULL_VERSION_NUMBER="$(git describe --tags `git rev-list --tags --max-count=1`)"
                  echo "version_number=$(echo "${FULL_VERSION_NUMBER}" | cut -c2- )" >> $GITHUB_ENV

                  # Create image tag for image being being replaced/refreshed/updated
                  echo "tag_old_image=$(echo "${FULL_VERSION_NUMBER}" | cut -c2- )_$(date +%Y-%m-%dT%H:%M:%S%z)" >> $GITHUB_ENV

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}
                  role-session-name: github_to_aws_deploy

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Tag current image version
              env:
                  IT_TAG: ${{ secrets.IT_IMAGE_TAG }}
              run: |
                  # Your commands that require AWS credentials
                  aws sts get-caller-identity

                  # Add a new tag to existing concordia image
                  APP_MANIFEST="$(aws ecr batch-get-image --repository-name concordia --image-ids imageTag=${IT_TAG} --output json | jq --raw-output --join-output '.images[0].imageManifest')"
                  aws ecr put-image --repository-name concordia --image-tag $version_number --image-manifest "$APP_MANIFEST"
                  # for testing...?
                  aws ecr describe-images --repository-name concordia --image-ids imageTag=$version_number

                  # Add a new tag to existing concordia/celerybeat image
                  BEAT_MANIFEST="$(aws ecr batch-get-image --repository-name concordia/celerybeat --image-ids imageTag=${IT_TAG} --output json | jq --raw-output --join-output '.images[0].imageManifest')"
                  aws ecr put-image --repository-name concordia/celerybeat --image-tag $version_number --image-manifest "$BEAT_MANIFEST"
                  # for testing...?
                  aws ecr describe-images --repository-name concordia/celerybeat --image-ids imageTag=$version_number

                  # Add a new tag to existing concordia/importer image
                  IMPORT_MANIFEST="$(aws ecr batch-get-image --repository-name concordia/importer --image-ids imageTag=${IT_TAG} --output json | jq --raw-output --join-output '.images[0].imageManifest')"
                  aws ecr put-image --repository-name concordia/importer --image-tag $version_number --image-manifest "$IMPORT_MANIFEST"
                  # for testing...?
                  aws ecr describe-images --repository-name concordia/importer --image-ids imageTag=$version_number

            # - name: Build, tag and push docker images ECR
            #   env:
            #       REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            #       IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
            #       CLUSTER: ${{ secrets.CLUSTER }}
            #       TARGET_SERVICE: ${{ secrets.TARGET_SERVICE }}
            #   run: |
            #       docker build -t concordia .
            #       docker tag concordia:latest $REGISTRY/concordia:$version_number
            #       docker tag concordia:latest $REGISTRY/concordia:$IMAGE_TAG
            #       docker push $REGISTRY/concordia:$version_number
            #       docker push $REGISTRY/concordia:$IMAGE_TAG

            #       docker build -t concordia/importer --file importer/Dockerfile .
            #       docker tag concordia/importer:latest $REGISTRY/concordia/importer:$version_number
            #       docker tag concordia/importer:latest $REGISTRY/concordia/importer:$IMAGE_TAG
            #       docker push $REGISTRY/concordia/importer:$version_number
            #       docker push $REGISTRY/concordia/importer:$IMAGE_TAG

            #       docker build -t concordia/celerybeat --file celerybeat/Dockerfile .
            #       docker tag concordia/celerybeat:latest $REGISTRY/concordia/celerybeat:$version_number
            #       docker tag concordia/celerybeat:latest $REGISTRY/concordia/celerybeat:$IMAGE_TAG
            #       docker push $REGISTRY/concordia/celerybeat:$version_number
            #       docker push $REGISTRY/concordia/celerybeat:$IMAGE_TAG

            #       aws ecs update-service --region ${{ env.AWS_REGION }} --force-new-deployment --cluster $CLUSTER --service $TARGET_SERVICE
